# Preparación de datos

**Conjunto de datos:** Dataset 10 - Mapa de departamentos

**Nombre de archivo:** departamentos.geojson

## 0. Inicialización

Instalar geopandas

In [1]:
!pip install geopandas

Requirement already satisfied: geopandas in c:\users\saras\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: numpy>=1.24 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.1.3)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (0.11.1)
Requirement already satisfied: packaging in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=2.0.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\users\saras\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.6.15)
Requirement already satisfied: six>=1.5 in c:\users\saras\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

Importaciones

In [2]:
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns

from tabulate import tabulate

Visualización de tablas y gráficas

In [3]:
sns.set_style("darkgrid")

def print_table(df):
    print(tabulate(df, headers='keys', tablefmt='simple_outline'))

Lectura y muestra del archivo

In [4]:
df = gpd.read_file('../data/original/departamentos.geojson')
df.head()

,DPTO_CCDGO,DPTO_CNMBR,VERSION,AREA,LATITUD,LONGITUD,TSP16_HOG,STP27_PERS,geometry
0,18,CAQUETÁ,2018,9.010301e+10,0.798556,-73.959468,116166,359602,"POLYGON ((-73.66007 1.6121, -73.65801 1.6073, ..."
1,19,CAUCA,2018,3.124291e+10,2.396834,-76.824233,432493,1243503,"POLYGON ((-76.05538 3.22339, -76.05244 3.21904..."
2,86,PUTUMAYO,2018,2.597628e+10,0.452260,-75.855912,107053,283197,"POLYGON ((-76.08489 1.05761, -76.07961 1.05597..."
3,76,VALLE DEL CAUCA,2018,2.066554e+10,3.858858,-76.518694,1267039,3789874,"MULTIPOLYGON (((-77.23806 4.0405, -77.22778 4...."
4,94,GUAINÍA,2018,7.128935e+10,2.727843,-68.816613,9953,44431,"POLYGON ((-69.84569 1.71388, -69.85141 1.70819..."

**1.** Eliminar columnas innecesarias

In [5]:
df = df.drop(columns=['VERSION', 'AREA', 'LATITUD', 'LONGITUD', 'TSP16_HOG', 'STP27_PERS'])
df.head()

,DPTO_CCDGO,DPTO_CNMBR,geometry
0,18,CAQUETÁ,"POLYGON ((-73.66007 1.6121, -73.65801 1.6073, ..."
1,19,CAUCA,"POLYGON ((-76.05538 3.22339, -76.05244 3.21904..."
2,86,PUTUMAYO,"POLYGON ((-76.08489 1.05761, -76.07961 1.05597..."
3,76,VALLE DEL CAUCA,"MULTIPOLYGON (((-77.23806 4.0405, -77.22778 4...."
4,94,GUAINÍA,"POLYGON ((-69.84569 1.71388, -69.85141 1.70819..."

**2.** Renombrar columnas

In [6]:
df = df.rename(columns={
    'DPTO_CCDGO':'Código departamento',
    'DPTO_CNMBR':'Departamento',
})
df.head()

,Código departamento,Departamento,geometry
0,18,CAQUETÁ,"POLYGON ((-73.66007 1.6121, -73.65801 1.6073, ..."
1,19,CAUCA,"POLYGON ((-76.05538 3.22339, -76.05244 3.21904..."
2,86,PUTUMAYO,"POLYGON ((-76.08489 1.05761, -76.07961 1.05597..."
3,76,VALLE DEL CAUCA,"MULTIPOLYGON (((-77.23806 4.0405, -77.22778 4...."
4,94,GUAINÍA,"POLYGON ((-69.84569 1.71388, -69.85141 1.70819..."

**3.** Mantener los municipios de Cundinamarca, Bogotá y Boyacá

In [7]:
codigos_dpto = ["25", "11", "15"]  # Cundinamarca, Bogotá, Boyacá
df = df[df['Código departamento'].isin(codigos_dpto)]
df

,Código departamento,Departamento,geometry
24,15,BOYACÁ,"POLYGON ((-72.04763 7.03823, -72.04088 7.03808..."
25,25,CUNDINAMARCA,"POLYGON ((-73.0525 4.73634, -73.06689 4.64101,..."
27,11,"BOGOTÁ, D.C.","POLYGON ((-74.15061 4.00483, -74.15443 4.01322..."

Resultado final

In [8]:
df

,Código departamento,Departamento,geometry
24,15,BOYACÁ,"POLYGON ((-72.04763 7.03823, -72.04088 7.03808..."
25,25,CUNDINAMARCA,"POLYGON ((-73.0525 4.73634, -73.06689 4.64101,..."
27,11,"BOGOTÁ, D.C.","POLYGON ((-74.15061 4.00483, -74.15443 4.01322..."

Exportar a CSV

In [9]:
df.to_file("../data/preparada/departamentos_final.geojson", driver="GeoJSON")