# Preparación de datos

**Conjunto de datos:** Dataset 11 - Malla vial

**Nombre de archivo:** vias.geojson

## 0. Inicialización

Instalar geopandas

In [1]:
!pip install geopandas

Requirement already satisfied: geopandas in c:\users\saras\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: numpy>=1.24 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.1.3)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (0.11.1)
Requirement already satisfied: packaging in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=2.0.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\users\saras\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.6.15)
Requirement already satisfied: six>=1.5 in c:\users\saras\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

Importaciones

In [2]:
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns

from tabulate import tabulate

Visualización de tablas y gráficas

In [3]:
sns.set_style("darkgrid")

def print_table(df):
    print(tabulate(df, headers='keys', tablefmt='simple_outline'))

Lectura y muestra del archivo

In [4]:
df = gpd.read_file('../data/original/vias.geojson')
df.head()

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,geometry
0,23579230,5113,primary,Avenida Calle 127,,F,0,1,T,F,"LINESTRING (-74.03144 4.70304, -74.03171 4.703..."
1,23579232,5114,secondary,Avenida Calle 63,,F,0,1,T,F,"LINESTRING (-74.0797 4.65229, -74.07863 4.6520..."
2,23592317,5114,secondary,Avenida Calle 72,,F,0,1,T,F,"LINESTRING (-74.07415 4.66828, -74.07357 4.667..."
3,23592322,5114,secondary,Avenida Calle 63,,F,30,0,F,F,"LINESTRING (-74.08853 4.65895, -74.08843 4.658..."
4,23592575,5113,primary,Transversal 60,,F,0,1,T,F,"LINESTRING (-74.07486 4.72304, -74.07486 4.722..."

**1.** Eliminar columnas innecesarias

In [5]:
df = df.drop(columns=['osm_id', 'code', 'ref', 'oneway', 'maxspeed', 'layer', 'bridge', 'tunnel'])
df.head()

,fclass,name,geometry
0,primary,Avenida Calle 127,"LINESTRING (-74.03144 4.70304, -74.03171 4.703..."
1,secondary,Avenida Calle 63,"LINESTRING (-74.0797 4.65229, -74.07863 4.6520..."
2,secondary,Avenida Calle 72,"LINESTRING (-74.07415 4.66828, -74.07357 4.667..."
3,secondary,Avenida Calle 63,"LINESTRING (-74.08853 4.65895, -74.08843 4.658..."
4,primary,Transversal 60,"LINESTRING (-74.07486 4.72304, -74.07486 4.722..."

**2.** Renombrar columnas

In [6]:
df = df.rename(columns={
    'fclass':'Tipo',
    'name':'Nombre',
})
df.head()

,Tipo,Nombre,geometry
0,primary,Avenida Calle 127,"LINESTRING (-74.03144 4.70304, -74.03171 4.703..."
1,secondary,Avenida Calle 63,"LINESTRING (-74.0797 4.65229, -74.07863 4.6520..."
2,secondary,Avenida Calle 72,"LINESTRING (-74.07415 4.66828, -74.07357 4.667..."
3,secondary,Avenida Calle 63,"LINESTRING (-74.08853 4.65895, -74.08843 4.658..."
4,primary,Transversal 60,"LINESTRING (-74.07486 4.72304, -74.07486 4.722..."

**3.** Renombrar los tipos

In [7]:
df['Tipo'] = df['Tipo'].replace({
    'trunk': 'Troncal',
    'primary': 'Primaria',
    'secondary': 'Secundaria',
})

Resultado final

In [8]:
df

,Tipo,Nombre,geometry
0,Primaria,Avenida Calle 127,"LINESTRING (-74.03144 4.70304, -74.03171 4.703..."
1,Secundaria,Avenida Calle 63,"LINESTRING (-74.0797 4.65229, -74.07863 4.6520..."
2,Secundaria,Avenida Calle 72,"LINESTRING (-74.07415 4.66828, -74.07357 4.667..."
3,Secundaria,Avenida Calle 63,"LINESTRING (-74.08853 4.65895, -74.08843 4.658..."
4,Primaria,Transversal 60,"LINESTRING (-74.07486 4.72304, -74.07486 4.722..."
...,...,...,...
15040,Secundaria,Vía San Pedro de Jagua-Santa María,"LINESTRING (-73.25933 4.82568, -73.25914 4.82589)"
15041,Primaria,Calle 6,"LINESTRING (-73.25832 4.8639, -73.25845 4.8641..."
15042,Secundaria,Vía San Pedro de Jagua-Santa María,"LINESTRING (-73.2639 4.80637, -73.2638 4.8065,..."
15043,Secundaria,Vía San Pedro de Jagua-Santa María,"LINESTRING (-73.264 4.80627, -73.2639 4.80637)"
15044,Secundaria,Calle 44C Sur,"LINESTRING (-74.12373 4.57449, -74.12371 4.57447)"

Exportar a CSV

In [9]:
df.to_file("../data/preparada/vias_final.geojson", driver="GeoJSON")