# Preparación de datos

**Conjunto de datos:** Dataset 9 - Mapa de municipios

**Nombre de archivo:** municipios.geojson

## 0. Inicialización

Instalar geopandas

In [51]:
!pip install geopandas

Requirement already satisfied: geopandas in c:\users\saras\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: numpy>=1.24 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.1.3)
Requirement already satisfied: pyogrio>=0.7.2 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (0.11.1)
Requirement already satisfied: packaging in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=2.0.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\users\saras\anaconda3\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saras\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\users\saras\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.6.15)
Requirement already satisfied: six>=1.5 in c:\users\saras\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

Importaciones

In [52]:
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns

from tabulate import tabulate

Visualización de tablas y gráficas

In [53]:
sns.set_style("darkgrid")

def print_table(df):
    print(tabulate(df, headers='keys', tablefmt='simple_outline'))

Lectura y muestra del archivo

In [ ]:
df = gpd.read_file('../data/original/municipios.geojson')
df.head()

,DPTO_CCDGO,MPIO_CCDGO,MPIO_CNMBR,MPIO_CDPMP,VERSION,AREA,LATITUD,LONGITUD,TSP16_HOG,STP27_PERS,geometry
0,18,001,FLORENCIA,18001,2018,2.547638e+09,1.749139,-75.558239,51430,156789,"POLYGON ((-75.40406 1.7695, -75.42726 1.75705,..."
1,18,029,ALBANIA,18029,2018,4.141221e+08,1.227865,-75.882327,1559,4514,"POLYGON ((-75.75674 1.18908, -75.76613 1.18638..."
2,18,094,BELÉN DE LOS ANDAQUÍES,18094,2018,1.191619e+09,1.500923,-75.875645,3161,9075,"POLYGON ((-75.77891 1.58257, -75.80857 1.53385..."
3,18,247,EL DONCELLO,18247,2018,1.106076e+09,1.791386,-75.193944,6129,17775,"POLYGON ((-75.34871 2.32353, -75.34474 2.31903..."
4,18,256,EL PAUJÍL,18256,2018,1.234734e+09,1.617746,-75.234043,5848,13014,"POLYGON ((-74.96432 1.44361, -74.96652 1.44076..."

**1.** Eliminar columnas innecesarias

In [55]:
df = df.drop(columns=['VERSION', 'AREA', 'LATITUD', 'LONGITUD', 'TSP16_HOG', 'STP27_PERS'])
df.head()

,DPTO_CCDGO,MPIO_CCDGO,MPIO_CNMBR,MPIO_CDPMP,geometry
0,18,001,FLORENCIA,18001,"POLYGON ((-75.40406 1.7695, -75.42726 1.75705,..."
1,18,029,ALBANIA,18029,"POLYGON ((-75.75674 1.18908, -75.76613 1.18638..."
2,18,094,BELÉN DE LOS ANDAQUÍES,18094,"POLYGON ((-75.77891 1.58257, -75.80857 1.53385..."
3,18,247,EL DONCELLO,18247,"POLYGON ((-75.34871 2.32353, -75.34474 2.31903..."
4,18,256,EL PAUJÍL,18256,"POLYGON ((-74.96432 1.44361, -74.96652 1.44076..."

**2.** Renombrar columnas

In [56]:
df = df.rename(columns={
    'DPTO_CCDGO':'Código departamento',
    'MPIO_CCDGO':'Código municipio',
    'MPIO_CNMBR':'Municipio',
    'MPIO_CDPMP': 'DIVIPOLA',
})
df.head()

,Código departamento,Código municipio,Municipio,DIVIPOLA,geometry
0,18,001,FLORENCIA,18001,"POLYGON ((-75.40406 1.7695, -75.42726 1.75705,..."
1,18,029,ALBANIA,18029,"POLYGON ((-75.75674 1.18908, -75.76613 1.18638..."
2,18,094,BELÉN DE LOS ANDAQUÍES,18094,"POLYGON ((-75.77891 1.58257, -75.80857 1.53385..."
3,18,247,EL DONCELLO,18247,"POLYGON ((-75.34871 2.32353, -75.34474 2.31903..."
4,18,256,EL PAUJÍL,18256,"POLYGON ((-74.96432 1.44361, -74.96652 1.44076..."

**3.** Mantener los municipios de Cundinamarca, Bogotá y Boyacá

In [57]:
codigos_dpto = ["25", "11", "15"]  # Cundinamarca, Bogotá, Boyacá
df = df[df['Código departamento'].isin(codigos_dpto)]
df

,Código departamento,Código municipio,Municipio,DIVIPOLA,geometry
637,15,001,TUNJA,15001,"POLYGON ((-73.34131 5.58404, -73.33206 5.57594..."
638,15,022,ALMEIDA,15022,"POLYGON ((-73.36451 5.01426, -73.35599 5.00347..."
639,15,047,AQUITANIA,15047,"POLYGON ((-72.71334 5.62496, -72.70864 5.61626..."
640,15,051,ARCABUCO,15051,"POLYGON ((-73.47154 5.82163, -73.47345 5.81683..."
641,15,087,BELÉN,15087,"POLYGON ((-72.81244 6.02325, -72.80642 6.01785..."
...,...,...,...,...,...
1114,25,260,EL ROSAL,25260,"POLYGON ((-74.23093 4.94456, -74.22432 4.93931..."
1115,25,473,MOSQUERA,25473,"POLYGON ((-74.17234 4.69617, -74.16779 4.68763..."
1116,25,740,SIBATÉ,25740,"POLYGON ((-74.23606 4.40041, -74.24502 4.40191..."
1117,25,290,FUSAGASUGÁ,25290,"POLYGON ((-74.28246 4.37943, -74.28907 4.36864..."
1118,25,662,SAN JUAN DE RIOSECO,25662,"POLYGON ((-74.57685 4.88894, -74.58287 4.88235..."

**4.** Añadir la columna de departamento

In [58]:
def get_department_name(code):
    department_names = {
        "11": "Bogotá",
        "15": "Boyacá",
        "25": "Cundinamarca"
    }
    return department_names.get(code, "Desconocido")

df['Departamento'] = df['Código departamento'].apply(get_department_name)
df = df[['Código departamento', 'Departamento', 'Código municipio', 'Municipio', 'DIVIPOLA', 'geometry']]
df.head()

,Código departamento,Departamento,Código municipio,Municipio,DIVIPOLA,geometry
637,15,Boyacá,001,TUNJA,15001,"POLYGON ((-73.34131 5.58404, -73.33206 5.57594..."
638,15,Boyacá,022,ALMEIDA,15022,"POLYGON ((-73.36451 5.01426, -73.35599 5.00347..."
639,15,Boyacá,047,AQUITANIA,15047,"POLYGON ((-72.71334 5.62496, -72.70864 5.61626..."
640,15,Boyacá,051,ARCABUCO,15051,"POLYGON ((-73.47154 5.82163, -73.47345 5.81683..."
641,15,Boyacá,087,BELÉN,15087,"POLYGON ((-72.81244 6.02325, -72.80642 6.01785..."

Resultado final

In [59]:
df

,Código departamento,Departamento,Código municipio,Municipio,DIVIPOLA,geometry
637,15,Boyacá,001,TUNJA,15001,"POLYGON ((-73.34131 5.58404, -73.33206 5.57594..."
638,15,Boyacá,022,ALMEIDA,15022,"POLYGON ((-73.36451 5.01426, -73.35599 5.00347..."
639,15,Boyacá,047,AQUITANIA,15047,"POLYGON ((-72.71334 5.62496, -72.70864 5.61626..."
640,15,Boyacá,051,ARCABUCO,15051,"POLYGON ((-73.47154 5.82163, -73.47345 5.81683..."
641,15,Boyacá,087,BELÉN,15087,"POLYGON ((-72.81244 6.02325, -72.80642 6.01785..."
...,...,...,...,...,...,...
1114,25,Cundinamarca,260,EL ROSAL,25260,"POLYGON ((-74.23093 4.94456, -74.22432 4.93931..."
1115,25,Cundinamarca,473,MOSQUERA,25473,"POLYGON ((-74.17234 4.69617, -74.16779 4.68763..."
1116,25,Cundinamarca,740,SIBATÉ,25740,"POLYGON ((-74.23606 4.40041, -74.24502 4.40191..."
1117,25,Cundinamarca,290,FUSAGASUGÁ,25290,"POLYGON ((-74.28246 4.37943, -74.28907 4.36864..."
1118,25,Cundinamarca,662,SAN JUAN DE RIOSECO,25662,"POLYGON ((-74.57685 4.88894, -74.58287 4.88235..."

Exportar a CSV

In [ ]:
df.to_file("../data/preparada/municipios_final.geojson", driver="GeoJSON")